#!/usr/bin/env bash

# Copyright © 2026 <https://github.com/technosf>
# SPDX-FileCopyrightText: © 2026 <https://github.com/technosf>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

##
## Flatpak repo run
##

set -e

flatpak --user run io.github.tuner_labs.tuner