#!/usr/bin/env bash

# Copyright © 2026 <https://github.com/technosf>
# SPDX-FileCopyrightText: © 2026 <https://github.com/technosf>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

##
## Flatpak debug run
##

set -e

flatpak-builder --run build-dir io.github.tuner_labs.tuner.debug.yml io.github.tuner_labs.tuner
